### ISSUE TITLE
Does not support CDK tokens properly

### ISSUE THREAD

**Issue by derekmurawsky** [DataDog/datadog-cdk-constructs#119]
## Expected Behavior

This should work, but it doesn't. 

```typescript
const datadogSite = ssm.StringParameter.fromStringParameterName(this, `${prefix}-datadog-site`, "/datadog/site");
const datadog = new Datadog(this, datadogName, {
      site: "us5.datadoghq.com", //datadogSite.stringValue, // Site is required for the sender extension layer set by extensionLayerVersion
      apiKeySecretArn: datadogAPIKey.secretArn,
      extensionLayerVersion: 25, // This is the datadog agent in lambda form. This is what sends stuff async to DD
      env: props.environmentName, // This sets the environment name for the lambda
      service: prefix, // This is the service name in DD
      version: packageVersion, // This is the version of the code we are running. This lets DD know about deployments.
      nodeLayerVersion: 81,
});
```

## Actual Behavior

![image](https://user-images.githubusercontent.com/3741839/181644220-9276bfab-1ce5-486d-b9de-821cf84a83fb.png)

Since the CDK passes this to a token at synth time, the checks do not recognize it and mark it as invalid. 

`Datadog Site Value: ${Token[TOKEN.532]}`

## Specifications

  - Datadog Lambda Layer version: NA
  - Node version: v16.15.1
  - datadog-cdk-constructs-vs: 0.3.4 - just installed today
  
## Stacktrace
  
  ```
/Users/.../node_modules/datadog-cdk-constructs-v2/src/common/datadogSharedLogic.ts:25
    throw new Error(
          ^
Error: Warning: Invalid site URL. Must be either datadoghq.com, datadoghq.eu, us3.datadoghq.com, us5.datadoghq.com, or ddog-gov.com.
    at Object.validateProps (/Users/dmurawsky/projects/croissant-services/node_modules/datadog-cdk-constructs-v2/src/common/datadogSharedLogic.ts:25:11)
    at new Datadog (/Users/dmurawsky/projects/croissant-services/node_modules/datadog-cdk-constructs-v2/src/datadog.ts:45:5)
    at new RetailerServicesStack (/Users/dmurawsky/projects/croissant-services/lib/retailer-services/retailer-services-stack.ts:432:21)
    at Object.<anonymous> (/Users/dmurawsky/projects/croissant-services/bin/croissant-services.ts:72:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/dmurawsky/projects/croissant-services/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/dmurawsky/projects/croissant-services/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

Subprocess exited with error 1
  ```

**Comment by jglien** [comment]
This is also the cause of a problem with the subscription filter names. It is valid (and even preferable) to pass a CDK token for the forwarder ARN. However, it is, of course, inappropriate to use the token to generate the subscription filter name since it changes each deployment. But this is exactly what [the code does](https://github.com/DataDog/datadog-cdk-constructs/blob/main/v2/src/forwarder.ts#L43).

**Comment by lizapressman** [comment]
Fix has been released
