### ISSUE TITLE
Cannot read properties of undefined (reading 'dockerPlatform')

### ISSUE THREAD

**Issue by leklement** [DataDog/datadog-cdk-constructs#171]
## Expected Behavior
Deploy AWS stack via CDK properly.

## Actual Behavior
Can't deploy AWS cdk stack as it fails on reading architecture props of lambda

## Steps to Reproduce the Problem

  1. install datadog-cdk-constructs-v2 
  2. add Datadog to stack
  3. call addLambdaFunctions with handlers
  4. deploy aws cdk ``` cdk deploy```

## Specifications
  - cdk version: 2.54.0 (build 9f41881)
  - Datadog Lambda Layer version: 1.6.0
  - Node version: 16.15.1
  
## Stacktrace
  
  ```
    lambdas.forEach((lam) => {
          ^
TypeError: Cannot read properties of undefined (reading 'dockerPlatform')
    at node_modules/datadog-cdk-constructs-v2/src/layer.ts:39:36
    at Array.forEach (<anonymous>)
    at Object.applyLayers (node_modules/datadog-cdk-constructs-v2/src/layer.ts:36:11)
    at Datadog.addLambdaFunctions (node_modules/datadog-cdk-constructs-v2/src/datadog.ts:67:9)


  ```

**Comment by sfirrin** [comment]
Hi @leklement thanks for opening this. I see the issue and will open a PR to fix today

**Comment by leklement** [comment]
Thank you 👏
